openapi: 3.0.1

info:
  title: Trestle API
  version: 2.0.0
  description: |
    ## Overview
    Trestle provides identity data for businesses.

    **Base URL**
    ```
    https://api.trestleiq.com
    ```

    ## Authentication
    All requests require an API key passed via `x-api-key` header.

servers:
  - url: https://api.trestleiq.com

security:
  - ApiKeyAuth: []

tags:
  - name: Reverse Phone API
    description: Phone number enrichment and validation
  - name: Caller Identification API
  - name: Smart CNAM API
  - name: Phone Validation API
  - name: Reverse Address API
  - name: Real Contact API
  - name: Phone Feedback API

paths:
  /3.2/phone:
    get:
      tags: [Reverse Phone API]
      summary: Reverse Phone API 3.2
      operationId: getPhone
      description: |
        **URL**
        ```
        https://api.trestleiq.com/3.2/phone?phone={phone}
        ```
      parameters:
        - $ref: '#/components/parameters/phone'
        - $ref: '#/components/parameters/countryHint'
        - $ref: '#/components/parameters/nameHint'
        - $ref: '#/components/parameters/postalCodeHint'
      responses:
        '200':
          description: Successful response
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '429':
          $ref: '#/components/responses/429'
      x-codeSamples:
        - lang: Shell
          label: cURL
          source: |
            curl --request GET               --url "https://api.trestleiq.com/3.2/phone?phone=2069735100"               --header "x-api-key: YOUR_API_KEY"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  parameters:
    phone:
      name: phone
      in: query
      required: true
      schema:
        type: string
      example: "2069735100"
    countryHint:
      name: phone.country_hint
      in: query
      schema:
        type: string
      example: US
    nameHint:
      name: phone.name_hint
      in: query
      schema:
        type: string
    postalCodeHint:
      name: phone.postal_code_hint
      in: query
      schema:
        type: string

  responses:
    400:
      description: Bad Request
    403:
      description: Forbidden
    429:
      description: Too Many Requests
